### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by maschs**
You should've waited a few minutes and let me cleanup. You integrated a version of the `.travis.yml` that is not working correctly (libsqlite3-dev is too old on 12.04) and you polluted your history with many test commits that were never meant to appear anywhere (just to trigger travis-ci).

You might want to consider doing what is evil beyond measure and `push --force` a cleaned history (squash my many commits into a single one).

### CODE REVIEW

**Comment by edrosten** [comment]
EEk! I did *not* mean to merge that branch and push.

**Comment by maschs** [comment]
Great, let me clean up this PR and you can just merge it and be done with it.

**Comment by edrosten** [comment]
I've rolled it back, which messes with history a little.

**Comment by Killili** [comment]
The history network graph needed a bit of ... interesting scenery i guess ;)

**Comment by maschs** [comment]
All tests passed, I think you can merge it now @edrosten :tada:

**Comment by Killili** [comment]
Nice did not know that this existed. THX

**Pull request merged**
