### PR TITLE
Error logging

### LINKED ISSUE #109: sqlite error log?
It would be nice to be able to interface with [sqlite3_config](https://sqlite.org/c3ref/config.html) for [error logging](https://sqlite.org/errlog.html) with [SQLITE_CONFIG_LOG](https://sqlite.org/c3ref/c_config_covering_index_scan.html).

Perhaps we would want to be able to code

    sqlite::error_log([&](int errcode, const char*msg) {
      std::clog<<"SQLITE ERROR " << errcode << ":" << msg << std:endl;
    });

What do you think?

I might provide a small patch if we agree on that API.

Thanks.

[Basile Starynkevitch](http://starynkevitch.net/Basile/)  :   `basile`  at `starynkevitch` dot `net`
(France)

### PR DESCRIPTION
**Pull request by zauguin**
Implement SQL error logging based on error classes.

Closes #109.

### CODE REVIEW

**Comment by zauguin** [comment]
@bstarynk Maybe you can help testing this?

**Comment by aminroosta** [comment]
@bstarynk Could you please comment :-)

**Comment by bstarynk** [comment]
I am not sure to understand how this should be used in practice. Maybe more comments could be useful. I am not sure to only want the error logging function to be activated *after* throwing some exception (but perhaps *before* that).

BTW, in my [melt-monitor](https://github.com/bstarynk/melt-monitor) (on github, e.g. commit [5b29edf1ef1b6621a0...](https://github.com/bstarynk/melt-monitor/commit/5b29edf1ef1b6621a0c0309fab71de8df07ffa1a)...) I have an additional wish. I am using extensively Ian Taylor's [libbacktrace](https://github.com/ianlancetaylor/libbacktrace), and I would like to print the backtrace *before* throwing any sqlite exception.

**Comment by bstarynk** [comment]
BTW, I would also like such new features to be testable with preprocessor flags, that is have perhaps `#define SQLITE_MODERNCPP_HAS_ERRORLOG 1` so that my application could code `#if SQLITE_MODERNCPP_HAS_ERRORLOG` ....

**Comment by zauguin** [comment]
@bstarynk This may be a documentation issue, why do you think the error logging is called after throwing the exception?

The error logging, based on the SQLite log functionality, is kind of independant of C++ exceptions. During execution, if SQLite detects an error, it calls the error log callback. Your handler is called with a `sqlite_exception` derived parameter to encode the error code, but this isn't a thrown exception. The exception is independently thrown at a later point.

So using libbacktrace should work, just replace the `cerr << ...` by your libbacktrace based error handling functionality.

**Comment by zauguin** [comment]
This feature is implemented in a separate header, so with most modern compiler (gcc >= 5, clang, VC++ 2015(?)) you can test for it with [`__has_include`](wg21.link/p0061). For example

```c++
#if __has_include(<sqlite_modern_cpp/log.h>)
...
#endif
```

**Pull request merged**
