### PR TITLE
Add support for custom SQL functions

### PR DESCRIPTION
**Pull request by zauguin**

### CODE REVIEW

**Comment by aminroosta** [comment]
@zauguin At first glance looks really interesting 👍 
I will take an in depth look at it tomorrow ;-)

**Comment by aminroosta** [comment]
@zauguin Is it possible to support blob columns using `std::vector<T>` as well?

**Comment by zauguin** [comment]
@aminroosta This is supported already.

**Comment by aminroosta** [comment]
@zauguin Oh, i missed that.
Please fix the merge conflicts and merge this PR.

Thanks ;-)

**Pull request merged**
