### PR TITLE
Fixed boost::optional support #25 and added Test

### PR DESCRIPTION
**Pull request by Killili**

### CODE REVIEW

**Comment by Killili** [comment]
@aminroosta pull it if your ok with the changes.

**Comment by aminroosta** [comment]
@Killili Great job, could you also update the README file.
Thanks :wink:

**Comment by aminroosta** [comment]
@Killili also in the `tests/boost_optional.cc` please use `exit( EXIT_FAILURE );` in the `catch(..){}` block.

**Comment by aminroosta** [comment]
@Killili In the test file you are using `id integer primary key autoincrement not null` to create `id` filed in the table, and in the `insert()` function you are explicitly setting the value of `id` filed with `db << "insert into test(id,val) values(?,?)" << id << val;`.

I was wondering if this is going to ignore **autoincrement** statement  or not? :smiley:

**Comment by Killili** [comment]
Copy&Paste is the natural enemy of good code.

As i said i will get there eventualy, next time dont merge it first makes fixing stuff easyer.

**Comment by aminroosta** [comment]
Sure.


Sent from Outlook Mobile






On Tue, Jan 12, 2016 at 3:34 AM -0800, "Killili" <notifications@github.com> wrote:





Copy&Paste is the natural enemy of good code.

As i said i will get there eventualy, next time dont merge it first makes fixing stuff easyer.

---

**Pull request merged**
