### PR TITLE
[RFC] Don't bundle SQLite

### PR DESCRIPTION
**Pull request by zauguin**
Why do we include the SQLite source code?
I couldn't find a place where it is used and it just becomes out-of-date.

### CODE REVIEW

**Comment by aminroosta** [comment]
@zauguin I agree with you that it becomes out of date.
But it's easier to clone the repo and start changing the source code / running tests ... right away.

**Comment by zauguin** [comment]
That's great, but wouldn't we have to change the Makefile to actually use the bundled SQLite?

**Comment by aminroosta** [comment]
Ah, I thought we are using these files in the Makefile!
Truth to be told i didn't wrote the `./configure` stuff :-)

@zauguin Thanks for the PR, go ahead and merge it if that's the case 👍

**Comment by zauguin** [comment]
Merged, if we ever need this, we can add it back together with the Makefile changes.

**Pull request merged**
