### PR TITLE
Ignore build products

### PR DESCRIPTION
**Pull request by tokuchan**
This commit updates git to ignore build-generated files and directories.

### CODE REVIEW

**Comment by Killili** [comment]
Hi,
i'm ok with most of this but why would we add "tests\" to ignore? We want those files in git.

**Comment by tokuchan** [comment]
Good point. What about the generated test files? Should I just list them explicitly?

Sean Spillane
tokuchan@gmail.com

へ　へ
の　の
　も
　へ

**Comment by Killili** [comment]
Best thing would be to have the build products stored somewhere else and ignore that path then i guess. Or exclude .cc files ... 

Its been a while since i build the project in its own directory so i dont know what files are generated.

**Comment by tokuchan** [comment]
I can add `!tests/*.cc` to un-ignore the source files. That would address the issue.

Sean Spillane
tokuchan@gmail.com

へ　へ
の　の
　も
　へ

**Comment by aminroosta** [comment]
Looks good to me, `!tests/*.cc` should be sufficient.

**Comment by tokuchan** [comment]
Cool.

**Pull request merged**
