### PR TITLE
Add test for try-catch-block

### PR DESCRIPTION
**Pull request by maschs**
@edrosten 
Does that look sufficient?

### CODE REVIEW

**Comment by maschs** [comment]
@edrosten 
Your idea was correct, using `std::uncaught_exception()` fixed the bug. The new test is using a temporary file as test database now.

**Comment by Killili** [comment]
@maschs  Thx

@aminroosta 
why is Travis-CI trying to compile us as a Ruby/Rake project?

**Comment by maschs** [comment]
You don't have `.travis.yml` defining what kind of project this is. So Travis is running a default set.

**Comment by Killili** [comment]
would be interesting, and i would never turn down help ;)

does/could it run the tests too?

**Comment by maschs** [comment]
Ofc, its fully configurable. You can tell it which compilers to use (multiple, too) and basically you can run anything you'd like.

**Pull request merged**
